### ISSUE TITLE
Pulling the rug out from under FOSS users

### ISSUE THREAD

**Issue by fluffynuts** [izhangzhihao/intellij-rainbow-brackets#2565]
I've used Rainbow Brackets for ages. The initial release was way good enough - just the paired-brackets support was great.

Since then, there's been a bunch of features added - of which I use none. However, I see now a change such that I need to pay for these features that I don't want - the plugin remains disabled unless I select to either pay, or go on a trial license, because I'm writing code in C#.

I understand the desire to make money off of your own software - and it's _your_ software to choose with what _you_ want to do - but I feel like the rug was pulled out from under existing users. The licensing info says that the free features remain free, but suddenly, C# isn't free. It's quite disappointing. The price, being in dollars, isn't (imo) a fair trade; neither is a recurring payment system for a user who has never, ever needed support - as I say, the initial offering was exactly what I was looking for.

**Comment by izhangzhihao** [comment]
Maintaining C#-related functions is quite time-consuming, you can search for related issues in this repo. And since 2022.3, many internal APIs of Rider has undergone fundamental changes, and the original code is almost unusable, so it is time-consuming to re-implement C#-related functions in the new version.

I'm not desperate for money, since you've been using this plugin for a few years you should know that the project has been around for over five years and it's all free. But this plug-in needs long-term maintenance, bug fixes, compatibility with new versions, answering user questions, etc. Open source software is not just free after writing the code, it is like a flower, which needs to be pruned and taxed, Catch insects. These take a lot of time to do. Frankly speaking, if I were just a simple open-source enthusiast, I am afraid that I would not maintain it from 1.0 (because 1.0 has satisfied all my demands), and this project has developed to this day. It was a huge effort and a lot of time, and I hope others understand that I need some support to make up for my time and energy investment.

Anyway, thanks for using this plugin.

**Comment by izhangzhihao** [comment]
By the way, [version 6.26](https://plugins.jetbrains.com/plugin/10080-rainbow-brackets/versions/stable/222834) will always be for free if you won't update this plugin, and your IDE(version before 2022.3). 

In Rider 2022.3 and above you will see this https://github.com/izhangzhihao/intellij-rainbow-brackets/issues/2529

YOU ALWAYS HAVE A CHOICE.

**Comment by fluffynuts** [comment]
> YOU ALWAYS HAVE A CHOICE.

I don't, really, do I? Because Rider moves on, and you've just stated that I have to stay with < 2022.3. So as long as I get  free ride from Jetbrains for doing opensource stuff, and as long as my company pays for a commercial license for their work, Rider will upgrade and you're saying that Rainbow Brackets will cease to work. In other words, there is no fallback for original users - as I've experienced: there's no way for me to say "yes, I like what originally existed and I don't need any more".

Rainbow variables? why even? All I wanted was what was in the name: "rainbow brackets". That part of the C# spec hasn't changed and won't change forever. Anyway, you've chosen your path, devious as it is. So long and thanks for all the fish.

**Comment by fluffynuts** [comment]
As stated in the original post: this is your code, your call, you owe me (and others) exactly nothing. However, this bait-and-switch mechanism to gain sponsors for your project is a bad idea, guaranteed to fail. IMO, you'd have better luck providing a donate url or something similar. If you'd done so, I probably would have, but what you did was simply rip out existing functionality, irrespective of user context. You will (probably) get some money in the short term, and it will dwindle. Good luck, have fun.

**Comment by izhangzhihao** [comment]
YES, really, do I? Because this plugin had to move on, and you could choose to move on or not.

Rainbow variables? lots of people like it.

**Comment by izhangzhihao** [comment]
> As stated in the original post: this is your code, your call, you owe me (and others) exactly nothing. However, this bait-and-switch mechanism to gain sponsors for your project is a bad idea, guaranteed to fail. IMO, you'd have better luck providing a donate url or something similar. If you'd done so, I probably would have, but what you did was simply rip out existing functionality, irrespective of user context. You will (probably) get some money in the short term, and it will dwindle. Good luck, have fun.

are you scaring me？ You have used this plugin for free for so many years, without a line of code contribution, without a dollar donation, do you have a little bit of respect for the authors of this plugin?

**Open source code is always open source, open source code is always free, this is my principle. But since 2022.3 the original open-source code is no longer available, mind you.**

that's all

**Comment by izhangzhihao** [comment]
**As long as you have contributed a line of code or donated a dollar before, you will definitely get a permanent free license, I promise. but you didn't**

**Comment by izhangzhihao** [comment]
It's very simple, my friend. I've already said what I should say. It doesn't make any sense for you to repeat it over and over again. It's just a waste of everyone's time. Don't just talk like a child.

BTW, you even never said "thanks" to me, I'm very sad.
