### ISSUE TITLE
PHPStorm notified me the plugin is not a production of JetBrains

### ISSUE THREAD

**Issue by samhdee** [izhangzhihao/intellij-rainbow-brackets#2646]
## Please check

- [ ] I already support this project.
- [ ] I already paid for this plugin.
- [x] I'm on a trial of this plugin.
- [x] This issue/feature request is not reported before.

(or if it is, I didn’t find it after searching throughly for it)

## Your programming languages

PHP

## Expected Behavior

PHPStorm should let me use the plugin without signaling a potential security/invalid source issue

## Current Behavior

I got an IDE internal error that says:

> Exception in plugin Rainbow Brackets {Link to disable plugin}
> This plugin is not a production of JetBrains. Please report the problem to [izhangzhihao](https://github.com/izhangzhihao)

## Code snippet for reproduce

[stacktrace.txt](https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12027158/stacktrace.txt)

## Your Environment

* Plugin version: 2023.3.1

```
PhpStorm 2023.1.3
Build #PS-231.9161.47, built on June 22, 2023
Licensed to GROUPE QUALICONSULT / Sam DHALEINE
You have a perpetual fallback license for this version.
Subscription is active until June 29, 2024.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1970M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.browser.jcef.gpu.disable=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.xrath.plugin.fold (1.5.0)
    com.intellij.ideolog (222.1.0.0)
    com.github.googee.laravelgenerator (3.1.7)
    com.herokuapp.vuesion (1.9.2)
    com.intellij.plugins.sublimetextkeymap (231.7515.9)
    Identifier Highlighter Reloaded (1.02.1)
    com.bartoszadamczyk.glowing-darcula (1.1.7)
    com.villains.intelij.plugin.trashpandatheme (2.0.5)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.1)
    String Manipulation (9.9.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    zielu.gittoolbox (500.0.13+213)
    some.awesome (1.14)
    com.midnightgamer.reactnative.snippts (0.1)
    net.rentalhost.plugins.php.hammer (0.22.2)
    com.intellij.php.codeigniter3 (0.6.0)
    net.rentalhost.plugins.laravel.hammer (0.2.1)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.4.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.253)
    com.github.iguissouma.nxconsole (0.58.0)
    dev.ekvedaras.laravelquery (4.0.2)
    com.niclas-van-eyk.laravel-make-integration (3.5.0)
    izhangzhihao.rainbow.brackets (2023.3.1)
```

**Comment by intellij-rainbow-brackets** [comment]
Off course this plugin is not a JetBrains  product.

Is there anything went wrong?
________________________________
From: Sam Dhee ***@***.***>
Sent: Wednesday, July 12, 2023 7:14:20 PM
To: izhangzhihao/intellij-rainbow-brackets ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [izhangzhihao/intellij-rainbow-brackets] PHPStorm notified me the plugin is not a production of JetBrains (Issue #2646)


Please check

  *    I already support this project.
  *    I already paid for this plugin.
  *    I'm on a trial of this plugin.
  *    This issue/feature request is not reported before.

(or if it is, I didn’t find it after searching throughly for it)

Your programming languages

PHP

Expected Behavior

PHPStorm should let me use the plugin without signaling a potential security/invalid source issue

Current Behavior

I got an IDE internal error that says:

Exception in plugin Rainbow Brackets {Link to disable plugin}
This plugin is not a production of JetBrains. Please report the problem to izhangzhihao<https://github.com/izhangzhihao>

Code snippet for reproduce

stacktrace.txt<https://github.com/izhangzhihao/intellij-rainbow-brackets/files/12027158/stacktrace.txt>

Your Environment

  *   Plugin version: 2023.3.1

PhpStorm 2023.1.3
Build #PS-231.9161.47, built on June 22, 2023
Licensed to GROUPE QUALICONSULT / Sam DHALEINE
You have a perpetual fallback license for this version.
Subscription is active until June 29, 2024.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1970M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true
    ide.browser.jcef.gpu.disable=true
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.xrath.plugin.fold (1.5.0)
    com.intellij.ideolog (222.1.0.0)
    com.github.googee.laravelgenerator (3.1.7)
    com.herokuapp.vuesion (1.9.2)
    com.intellij.plugins.sublimetextkeymap (231.7515.9)
    Identifier Highlighter Reloaded (1.02.1)
    com.bartoszadamczyk.glowing-darcula (1.1.7)
    com.villains.intelij.plugin.trashpandatheme (2.0.5)
    com.mallowigi (90.0.0)
    mobi.hsz.idea.gitignore (4.5.1)
    String Manipulation (9.9.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    zielu.gittoolbox (500.0.13+213)
    some.awesome (1.14)
    com.midnightgamer.reactnative.snippts (0.1)
    net.rentalhost.plugins.php.hammer (0.22.2)
    com.intellij.php.codeigniter3 (0.6.0)
    net.rentalhost.plugins.laravel.hammer (0.2.1)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.annotation (9.4.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.253)
    com.github.iguissouma.nxconsole (0.58.0)
    dev.ekvedaras.laravelquery (4.0.2)
    com.niclas-van-eyk.laravel-make-integration (3.5.0)
    izhangzhihao.rainbow.brackets (2023.3.1)


―

**Comment by samhdee** [comment]
I understand this plugin is not a JetBrains product, my issue was with the fact that PHPStorm was raising a security concern that it had never had before.

However I found out it was a Java issue. I reinstalled Java and it solved my problem.

**Comment by samhdee** [comment]
Correction: reinstalling Java didn’t solve the issue but it appears PHPStorm has a problem with any plugin that’s not a product of theirs. It’s not a problem specific to Rainbow Brackets, so the issue is closed anyway.
