### ISSUE TITLE
Option to only colorize parents of cursor's scope

### ISSUE THREAD

**Issue by solidfox** [izhangzhihao/intellij-rainbow-brackets#70]
## Expected Behavior
The Atom package rainbow-delimiters has this behavior.
When editing code only the brackets relevant to the determine the current scope are colorized. Much like the new highlight scope feature but all parent scopes are highlighted and it is only highlighted through the colored brackets. Other brackets are heavily toned down.

![Image of Yaktocat](https://www.dropbox.com/s/irl1ee6zpijyb40/Screenshot%202018-05-22%2017.44.05.png?raw=1)

## Your Environment

* Plugin version:
* IDE & Operating System version, comment your env as below(go to "About IntelliJ IDEA" -> click the "copy" icon):

```
IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
JRE: 1.8.0_152-release-1136-b38 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4
```

**Comment by nioncode** [comment]
I'm looking for a combination of rainbow brackets and [HighlightBracketPair](https://plugins.jetbrains.com/plugin/10465-highlightbracketpair), i.e. when being inside a scope, rainbow brackets should automatically highlight the matching brackets, while fading out the inner brackets.

Is your proposal exactly this or did I misunderstand your feature request?

**Comment by izhangzhihao** [comment]
Have you tried scope highlighting? 

![](https://user-images.githubusercontent.com/10737066/40235004-642dfe54-5adb-11e8-9fd7-648b92fab8f5.gif)

**Comment by nioncode** [comment]
Yes, but I think this should be done automatically without having to press a modifier key and clicking with the mouse.
However, if this is done automatically just by moving the cursor around, I think this will be too distracting and I'd prefer to only have the scope's brackets highlighted instead of fading out all outer code.

Summary:
- keep scope highlighting as is (still good for focusing exactly on one scope) and this can be done manually with clicking
- add a 'highlight scope brackets/parentheses/...' feature that always highlights the outer scope's matching brackets etc.

I was wondering if this feature request already is about exactly that or if it is something else and I should create a new issue for it.

**Comment by izhangzhihao** [comment]
I don't think it's same, you can check: https://atom.io/packages/rainbow-delimiters
